# 配置网关
spring:
  cloud:
    gateway:
      routes:
        - id: notice-service  #服务名称，路由规则名称，不重复就行
          uri: lb://notice-service  #路径的服务名称
          predicates:
            - Path=/notice/**  # 访问  通知  路径转发用户服务
        - id: product-service # 此名称随意定义
          uri: lb://product-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/product/** # 访问product相关,转发到product服务
        - id: tset-service # 此名称随意定义
          uri: lb://test-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/test/** # 访问product相关,转发到product服务
        - id: manage-service # 此名称随意定义
          uri: lb://manage-service #使用负载均衡,调用服务名,这是服务名
          predicates:
            - Path=/manage/** # 访问product相关,转发到product服务

      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站指明端口的跨域请求
              - "http://localhost:5173"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期